data:
  train_batch_size: 64
  micro_batch_size: null # will be deprecated, use micro_batch_size_per_gpu
  micro_batch_size_per_gpu: 1  # this is also val batch size
  train_files: /workspace/sft/kimina_SFT_train.jsonl
  val_files: /workspace/sft/kimina_SFT_val.jsonl
  # Multi-turn settings
  multiturn:
    enable: false  # Set to true to use multi-turn dataset
    messages_key: messages  # Key for messages list in multi-turn mode
  max_length: 16384
  truncation: right
  balance_dp_token: False
  chat_template: null
  custom_cls:
    path: null
    name: null
model:
  partial_pretrain: /workspace/sft/kimina-7b
  fsdp_config:
    wrap_policy:
      min_num_params: 0
    cpu_offload: False
    offload_params: False
  external_lib: null
  enable_gradient_checkpointing: False
  trust_remote_code: False
  lora_rank: 0  # Set to positive value to enable LoRA (e.g., 32)
  lora_alpha: 16  # LoRA scaling factor
  target_modules: all-linear  # Target modules for LoRA adaptation
  use_liger: False
optim:
  lr: 1e-5
  betas: [0.9, 0.95]
  weight_decay: 0.01
  warmup_steps_ratio: 0.1
  clip_grad: 1.0
  lr_scheduler: cosine
ulysses_sequence_parallel_size: 4
use_remove_padding: True
trainer:
  default_local_dir: /workspace/sft/checkpoints
  default_hdfs_dir: null
  resume_path: null
  project_name: lean
  experiment_name: lean-test
  total_epochs: 2
  total_training_steps: null
  logger: ['console']
  seed: 1
